api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("getall", views.getall.as_view(), name="getall"),
    path("getone/<int:id>", views.getone.as_view(), name="getone"),  # send get request
    path("create", views.getone.as_view(), name="create"),  # send post req
    path("update/<str:id>", views.updateone.as_view(), name="update"),
    path(
        "delete/<int:id>", views.getone.as_view(), name="delete"
    ),  # send delete requset
]

cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("<str:ip>", views.cart, name="cart"),
    path("ajax_url/", views.update_quant, name="ajax_url"),
]

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("manage_products/<int:id>", views.manage_products, name="manage_products"),
    # path("getone/<int:id>", views.getone, name="getone"),
    path("delete_prod/<int:id>/<int:seller_id>", views.delete_prod, name="delete_prod"),
    path("update_prod/<int:id>", views.update_prod, name="update_prod"),
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include(("products.urls", "products"), namespace="products")),
    path("", include("home.urls")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/", include("api.urls")),
    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
]
urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

urlpatterns = urlpatterns + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

cart/models.py
from django.db import models

# Create your models here.
from django.db import models
from datetime import datetime

from products.models import Products


class Cart(models.Model):
    userip = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(
        blank=True, null=True, auto_now=True
    )  # auto_now fields are updated to the current timestamp every time an object is saved

    def __str__(self):
        return self.userip


class CartItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price_ht = models.FloatField(blank=True)
    cart = models.ForeignKey("Cart", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.product)  # self.client + " - " + self.product

products/models.py
from django.db import models

from users.models import User

from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
import os
import uuid
from django.urls import path

# Create your models here.


class Products(models.Model):
    name = models.CharField(max_length=100)
    seller = models.ForeignKey(User, on_delete=models.PROTECT, default=1)
    cost = models.FloatField()
    img = models.ImageField(upload_to="pics")
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)  # default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Products"
        # Add verbose name
        verbose_name = "Products List"


@receiver(models.signals.post_delete, sender=Products)
def auto_delete_file_on_delete(
    sender, instance, **kwargs
):  # delete song from audio folder
    """
    Deletes file from filesystem
    when object is deleted.
    """
    print("we are inside post delete")
    if instance.img:
        if os.path.isfile(instance.img.path):
            os.remove(instance.img.path)


@receiver(
    models.signals.pre_save, sender=Products
)  # deletes old img if changed during update
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when object is updated
    with new file."""

    if not instance.pk:
        return False
        print("returning now 1")
    try:
        old_img = sender.objects.get(pk=instance.pk).img
        print("we are in signal", old_img)
    except sender.DoesNotExist:
        print("returning now 2")
        return False
    if not old_img:
        print("returning now 3")
        return
    new_img = instance.img

    print("new img is", new_img)
    if not old_img == new_img:
        print("we are inside pre save")
        if os.path.isfile(old_img.path):
            os.remove(old_img.path)

cart/views.py
from django.shortcuts import render
from .models import Cart, CartItem
from django.http import JsonResponse
import json
import ast
from django.http import HttpResponse
from products.models import Products

# Create your views here.


def cart(request, ip):
    crt = Cart.objects.get(userip=ip)
    prods = CartItem.objects.filter(cart=crt)

    return render(request, "cart.html", {"products": prods})


def update_quant(request):

    prod_id = request.GET.get("prod_id")
    action = request.GET.get("action")
    change = request.GET.get("change")
    cartitem = request.GET.get("cartitem")
    prod = Products.objects.get(id=prod_id)
    if action == "add":
        prod.quantity = prod.quantity - 1
        request.sessions["items"] = request.session["items"] - 1
    else:
        prod.quantity = prod.quantity + 1
        request.sessions["items"] = request.session["items"] + 1
    prod.save()
    item = CartItem.objects.get(id=cartitem)
    item.quantity = change
    if item.quantity == 0:
        item.save()
    else:
        item.delete()
    return HttpResponse(prod_id)  # (context)

products/views.py
from django.shortcuts import redirect, render
from .models import Products
import requests
from django import forms
from django.contrib import messages
from api.serializers import ProductUpdateSerializer


class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ["name", "img", "cost", "quantity", "is_active"]


def delete_prod(request, id, seller_id):

    id = id
    address = "http://127.0.0.1:8000/api/delete/" + str(id)
    resp = requests.delete(
        address, headers={"Authorization": "Bearer " + request.session["jwt"]}
    ).text
    print(resp)
    return redirect("/products/manage_products/" + str(seller_id))


def update_prod(request, id):

    id = id
    address = "http://127.0.0.1:8000/api/getone/" + str(id)

    prod = requests.get(
        address, headers={"Authorization": "Bearer " + request.session["jwt"]}
    ).json()
    # product = Products.objects.get(id=id)
    seller = prod["seller"]

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES or None, instance=prod)
        if form.is_valid():
            print("trying to see form's img", form.cleaned_data["img"])
            resp = requests.post(
                "http://127.0.0.1:8000/api/update/" + str(id),
                files={"img": form.cleaned_data["img"]},  # request.FILES["img"]},
                headers={"Authorization": "Bearer " + request.session["jwt"]},
                data=form.data,
            )
            # print(resp)
            return redirect("/products/manage_products/" + str(seller))
        else:
            return redirect("/products/manage_products/" + str(seller))
    else:
        form = ProductForm(instance=prod)
        # instance={
        #     "name": prod["name"],
        #     "img": prod["img"],
        #     "cost": prod["cost"],
        #     "quantity": prod["quantity"],
        #     "is_active": prod["is_active"],
        # }

        # }prod)

    return render(request, "update_prod.html", {"prod": prod})  # , "form": form})


def manage_products(request, id):
    myform = ProductForm()
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES or None)
        if form.is_valid():
            print(form.data)
            requests.post(
                url="http://127.0.0.1:8000/api/create",
                headers={"Authorization": "Bearer " + request.session["jwt"]},
                files={"img": request.FILES["img"]},
                data=form.data,
            )

        else:
            messages.error(request, "Invalid input!")

    address = "http://127.0.0.1:8000/api/getall"

    myProds = requests.get(
        address, headers={"Authorization": "Bearer " + request.session["jwt"]}
    ).json()
    # print(myProds)
    return render(
        request, "manage_products.html", {"products": myProds, "form": myform}
    )

templates/cart.html
{% include "header.html"%}
{% load static %}
<div class="page-heading products-heading header-text">
    <div class="container">
<h6>Hello, {{ request.session.userip }}</h6>

{% for prod in products%}
<div class="row">
    <div class="col-lg-3 col-md-3 all des product-item">
        <a href="#"><img width='1rem' src="{{prod.product.img.url}}" alt=""></a>
        <div class="down-content">
            <a href="#">
                <h4>{{prod.product.name}}</h4>
                
            </a>
            <h6 id='id_cartitem{{prod.product.id}}'>{{prod.id}}</h6>
            <h4 class='cost' id='id_cost{{prod.product.id}}'>{{prod.product.cost}}</h4>
            <h5 style='color:red' class='dec'  id='id_dec{{prod.product.id}}'>-</h5>
            <h5 class='quant' style='color:white' id='id_quant{{prod.product.id}}'>{{prod.quantity}}</h5>
            <h5 style='color:blue' class='inc' id='id_inc{{prod.product.id}}'>+</h5>
            
        </div>
    </div>
</div>

{%endfor%}
<h6 id="total"></h6>
<!-- <a href="#"><button>Pay now</button></a> -->


{% include "footer.html"%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    
    $(document).ready(function () {
        totcost = 0
         $(".quant").each(function (index, element) {
            target = this.id.slice(8)
            quantity= parseInt(element.textContent)
            
            cost = $("#id_cost"+target).text()
            
            item_tot_cost = parseInt(quantity) * parseFloat(cost);
            totcost = totcost + item_tot_cost
            $("#total").text(totcost)
            
        });
        
        function updatequantity(prod_id,change,action,cartitem)
        {
            $.ajax({
                url: "{% url 'ajax_url' %}",
                data: {
                    'prod_id': prod_id,
                    'change': change,
                    'action':action,
                    'cartitem':cartitem
                },
                success: function (data) {
                    console.log("quantity updated")
                    
                }
            });
        }
       $(".inc").click(function () {
           target = this.id.slice(6)
           cartitem =  $('#id_cartitem' + target).text();
           alert(cartitem)
           val = $('#id_quant'+target).html();
           newval = parseInt(val)+1
           $('#id_quant' + target).html(newval)
           updatequantity(target, newval,'add',cartitem)
        })
        $(".dec").click(function () {
            target = this.id.slice(6)
            cartitem = $('#id_cartitem' + target).textContent;
            
            val = $('#id_quant' + target).html();
            newval = parseInt(val) - 1
            $('#id_quant' + target).html(newval)
            updatequantity(target ,newval,'sub',cartitem)
        })
    });
</script>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    
    {% block title %}{% endblock %}
    <!-- Bootstrap core CSS -->
    <link href={% static "vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
<!--

TemplateMo 546 Sixteen Clothing

https://templatemo.com/tm-546-sixteen-clothing

-->

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href={% static "assets/css/fontawesome.css" %}>
    <link rel="stylesheet" href={% static "assets/css/templatemo-sixteen.css" %}>
    <link rel="stylesheet" href={% static "assets/css/owl.css" %}>

  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Sixteen <em>Clothing</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'view_products' %}">Our Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
              </li>
              
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">{{user.email}} Logout</a>
              
              </li>
              {% if user.is_admin %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:manage_products' user.id %}">Manage Products</a>
              
              </li>
              {% endif %}
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              
              </li>
              {% endif %}

              <li class="nav-item">
                <a class="nav-link" href="{% url 'cart' request.session.userip %}">
                  <i class="fa fa-shopping-cart"></i>
                  <span class='badge badge-warning' id='lblCartCount'> {{request.session.items }} </span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

templates/index.html
{% include "header.html" %}

    {% block title %}<title>Shopping website</title>{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    {% load static %}
    <div class="banner header-text">
      <div class="owl-banner owl-carousel">
        <div class="banner-item-01">
          <div class="text-content">
            <h4>Best Offer</h4>
            <h2>New Arrivals On Sale</h2>
          </div>
        </div>
        <div class="banner-item-02">
          <div class="text-content">
            <h4>Flash Deals</h4>
            <h2>Get your best products</h2>
          </div>
        </div>
        <div class="banner-item-03">
          <div class="text-content">
            <h4>Last Minute</h4>
            <h2>Grab last minute deals</h2>
          </div>
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <div class="latest-products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>Latest Products</h2>
              <a href="{% url 'view_products' %}">view all products <i class="fa fa-angle-right"></i></a>
            </div>
          </div>
         
          
        </div>
      </div>
    </div>

    <div class="best-features">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <h2>About Shopping Clothing</h2>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-content">
              <h4>Looking for the best products?</h4>
              <p><a rel="nofollow" href="https://templatemo.com/tm-546-sixteen-clothing" target="_parent">This template</a> is free to use for your business websites. However, you have no permission to redistribute the downloadable ZIP file on any template collection website. <a rel="nofollow" href="https://templatemo.com/contact">Contact us</a> for more info.</p>
              <ul class="featured-list">
                <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                <li><a href="#">Consectetur an adipisicing elit</a></li>
                <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                <li><a href="#">Corporis, omnis doloremque</a></li>
                <li><a href="#">Non cum id reprehenderit</a></li>
              </ul>
              <a href="about.html" class="filled-button">Read More</a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-image">
              <img src={%static "assets/images/feature-image.jpg" %} alt="">
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="inner-content">
              <div class="row">
                <div class="col-md-8">
                  <h4>Creative &amp; Unique <em>Sixteen</em> Products</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque corporis amet elite author nulla.</p>
                </div>
                <div class="col-md-4">
                  <a href="#" class="filled-button">Purchase Now</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    {% include "footer.html" %}

templates/login.html
{% include "header.html" %}

    {% block title %}<title>Shopping website</title>{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    {% load static %}
    <div class="page-heading products-heading header-text">
        <div class="container">
          <div class="row">
        <form action="login" method="POST">
            {% csrf_token %}
            <input type="text" name="email" placeholder="email"><br>
            <input type="password" name="password" placeholder="password"><br>
            <button type="submit"> Login </button>
        </form>

    
        <div>
            {% for message in messages %}
            <h3>
                {{message}}
            </h3>
            {% endfor %}
        </div>
        <div >
            Not a user? <a href="{% url 'register'%}">Register here</a>
        </div>
        </div>
        </div>
    </div>
   
{% include "footer.html" %}

templates/manage_products.html
{% include "header.html" %}

    {% block title %}<title>Products Page</title>{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    {% load static %}
    <!-- Page Content -->
    

    <div class="page-heading about-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>Welcome hello {{user.email}}</h4>
              
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="products">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-4 all des">
            <p>Add product</p>
          </div>
            <div class="col-lg-4 col-md-4 all des">
            <form action="" method="POST" enctype="multipart/form-data">
            
              {% csrf_token %}
            
              {{ form.as_p }}
              <input id="submit" class="btn" type="submit"><br>
            
            
            </form>
            </div>
          </div>
          <div class='row'><p><strong>Your products</strong></p></div>
          <div class="row grid">
            
            {% for prod in products %}
            <div class="col-lg-4 col-md-4">
              <div class="product-item">
                <a href="#"><img style='width:100px;height: 100px' src="{{prod.img}}" alt=""></a>
                <div class="down-content">
                  <a href="#">
                    <h4>{{prod.name}}</h4>
                  </a>
                  <h6>${{prod.cost}}</h6>
                  <h4>Inventory: {{prod.quantity}}</h4>
                  <h5 style="color: brown;">Active:{{prod.is_active}}</h5>
                  <a href='/products/delete_prod/{{prod.id}}/{{user.id}}'><button>Delete</button></a>
                  <!-- <a href='/products/update_prod/{{prod.id}}'><button>Update</button></a> -->
                  <a href='http://127.0.0.1:8000/api/update/{{prod.id}}'><button>Update</button></a>
          
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        
          
        
        </div>
      </div>
<!--     
    
    {% include "footer.html"%} -->

templates/products.html
{% include "header.html" %}

    {% block title %}<title>Products Page</title>{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    {% load static %}
    <!-- Page Content -->
    <div class="page-heading products-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>new arrivals</h4>
              <h2>sixteen products</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" data-filter="*">All Products</li>
                  <li data-filter=".des">Featured</li>
                  <li data-filter=".dev">Flash Deals</li>
                  <li data-filter=".gra">Last Minute</li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                    {% for prod in products %}
                    {% if prod.is_active %}
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <a href="#"><img src="{{prod.img.url}}" %} alt=""></a>
                        <div class="down-content">
                          <a href="#"><h4>{{prod.name}}</h4></a>
                          <h6>${{prod.cost}}</h6>
                          <p>{{prod.description}}</p>
                          <a href="{% url 'buynow' prod.id %}"><button>Buy now</button></a>
                          <a href="{% url 'addtocart' prod.id %}"><button>Add to cart</button></a>
                         
                        </div>
                      </div>
                    </div>
                    {% endif %}
                  {% endfor %}  
                  </div>
                </div>
            </div>
          </div>
          <div class="col-md-12">
            <ul class="pages">
              <li><a href="#">1</a></li>
              <li class="active"><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    
    {% include "footer.html"%}

templates/register.html
{% include "header.html" %}

    {% block title %}<title>Register</title>{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    {% load static %}
    <div class="page-heading products-heading header-text">
    <div class="container">
        <form action='register' method='post'>
            {% csrf_token %}
            
            Email: <input type="email" name="email" placeholder="abc@xyz.com"><br>
            Password: <input type="password" name="password1" placeholder="Password"><br>
            Password: <input type="password" name="password2" placeholder="Confirm password"><br>
            Is_Admin: <select name='is_admin'>
                <option value=True >Seller</option>
                <option selected value=False>Buyer</option>
            </select>
            <button type="submit" name="Sumbit">Submit </button>
    
        </form>
        <div>
            {% for message in messages %}
            <h3>
                {{message}}
            </h3>
            {% endfor %}
        </div>
    </div>
</div>
{% include "footer.html" %}

templates/update_prod.html
{% include "header.html" %}
{% load rest_framework %}
    {% block title %}<title>Products Page</title>{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    {% load static %}
    <!-- Page Content -->
    

    <div class="page-heading about-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>Welcome {{user.email}}</h4>
              
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="products">
      <div class="container">
        <div class="row">
          <div><h1>Update product</h1></div>
          
          <form action="{% url 'update' prod.id %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {% render_form serializer %}

           
            <input type="submit" value="Save">
          </form>
          
          </div>
          
        
          
        
        </div>
      </div>
    </div>

    
    {% include "footer.html"%}